version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "9078:9078"
    networks:
      - hello_network

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "8868:80"
    depends_on:
      - backend
    networks:
      - hello_network

networks:
  hello_network:
    driver: bridge
